tclmode

# Generated by Genus(TM) Synthesis Solution 21.12-s068_1, revision 1.557b.beta
# Generated on: Sun Mar 12 08:08:23 PDT 2023 (Sun Mar 12 15:08:23 UTC 2023)

set_screen_display -noprogress
set_dofile_abort exit

### Alias mapping flow is enabled. ###
# Root attribute 'wlec_rtl_name_mapping_flow' was 'false'.
# Root attribute 'alias_flow'                 was 'true'.

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         true

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required &&
    $wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set logfile logs/intermediate2final.lec.log

set_log_file $logfile -replace

usage -auto -elapse

set_mapping_method -sensitive

set_verification_information fv_map_scr1_pipe_top_mv_db

read_implementation_information fv/scr1_pipe_top -golden fv_map -revised scr1_pipe_top_mv

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set_lowpower_option -native_1801
set_lowpower_option -golden_analysis_style  post_synthesis
set_lowpower_option -revised_analysis_style post_synthesis

set env(RC_VERSION)     "21.12-s068_1"
set env(CDN_SYNTH_ROOT) "/p/gtkit/tools/eda_tools/genus/genus_21.12-s068_1/tools.lnx86"
set CDN_SYNTH_ROOT      "/p/gtkit/tools/eda_tools/genus/genus_21.12-s068_1/tools.lnx86"
set env(CW_DIR) "/p/gtkit/tools/eda_tools/genus/genus_21.12-s068_1/tools.lnx86/lib/chipware"
set CW_DIR      "/p/gtkit/tools/eda_tools/genus/genus_21.12-s068_1/tools.lnx86/lib/chipware"
set_multiplier_implementation boothrca -both

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_notranslate_modules -library -both sram_32_1024_scl180

add_search_path . -library -both
read_library -liberty -both -lp all \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_4096X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_2048X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/pdkIO.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_512X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_136X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_128X16_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_1024X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM1_4096X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM1_256X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM1_1024X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_128X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../riscvCoreSyntaCore1/ramInputs/sram_32_1024_max_1p8V_25C.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../riscvCoreSyntaCore1/ramInputs/i2c_top.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../riscvCoreSyntaCore1/ramInputs/uart.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_4096X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_2048X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/pdkIO.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_512X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_136X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_128X16_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_1024X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM1_4096X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM1_256X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM1_1024X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../technology/45/lib/max/MEM2_128X32_slow.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../riscvCoreSyntaCore1/ramInputs/sram_32_1024_max_1p8V_25C.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../riscvCoreSyntaCore1/ramInputs/i2c_top.lib \
    /nfs/site/disks/vmisd_vclp_efficiency/rcg/test/cadence/venvRcg/AsicMethadology/synthesis/../riscvCoreSyntaCore1/ramInputs/uart.lib

read_design -verilog95   -golden -lastmod -noelab fv/scr1_pipe_top/fv_map.v.gz
elaborate_design -golden -root {scr1_pipe_top}

read_design -verilog95   -revised -lastmod -noelab outputs/scr1_pipe_top_m.v
elaborate_design -revised -root {scr1_pipe_top}

read_power_intent -1801 -golden fv/scr1_pipe_top/fv_map.upf
read_power_intent -1801 -revised ../scripts/genus/block.upf

#add_name_alias fv/scr1_pipe_top/fv_map.singlebit.original_name.alias.json.gz -golden
#set_mapping_method -alias -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge
set_flatten_model -gated_clock

#add_name_alias fv/scr1_pipe_top/scr1_pipe_top_mv.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff dlat -both

# Reports the quality of the implementation information.
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
    check_verification_information
}

set_analyze_option -auto -report_map

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

# Reports how effective the implementation information was.
# This command is only available with LEC 18.20-d330 or later.
set lec_version_required "18.20330"
if {$lec_version >= $lec_version_required} {
    report_implementation_information
}

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
# This command is available with LEC 19.10-p100 or later.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required} {
analyze_results -logfiles $logfile
}

vpxmode

exit -f
