
//input ports
add mapped point pipe_rst_n pipe_rst_n -type PI PI
add mapped point clk clk -type PI PI
add mapped point imem2pipe_req_ack_i imem2pipe_req_ack_i -type PI PI
add mapped point imem2pipe_rdata_i[31] imem2pipe_rdata_i[31] -type PI PI
add mapped point imem2pipe_rdata_i[30] imem2pipe_rdata_i[30] -type PI PI
add mapped point imem2pipe_rdata_i[29] imem2pipe_rdata_i[29] -type PI PI
add mapped point imem2pipe_rdata_i[28] imem2pipe_rdata_i[28] -type PI PI
add mapped point imem2pipe_rdata_i[27] imem2pipe_rdata_i[27] -type PI PI
add mapped point imem2pipe_rdata_i[26] imem2pipe_rdata_i[26] -type PI PI
add mapped point imem2pipe_rdata_i[25] imem2pipe_rdata_i[25] -type PI PI
add mapped point imem2pipe_rdata_i[24] imem2pipe_rdata_i[24] -type PI PI
add mapped point imem2pipe_rdata_i[23] imem2pipe_rdata_i[23] -type PI PI
add mapped point imem2pipe_rdata_i[22] imem2pipe_rdata_i[22] -type PI PI
add mapped point imem2pipe_rdata_i[21] imem2pipe_rdata_i[21] -type PI PI
add mapped point imem2pipe_rdata_i[20] imem2pipe_rdata_i[20] -type PI PI
add mapped point imem2pipe_rdata_i[19] imem2pipe_rdata_i[19] -type PI PI
add mapped point imem2pipe_rdata_i[18] imem2pipe_rdata_i[18] -type PI PI
add mapped point imem2pipe_rdata_i[17] imem2pipe_rdata_i[17] -type PI PI
add mapped point imem2pipe_rdata_i[16] imem2pipe_rdata_i[16] -type PI PI
add mapped point imem2pipe_rdata_i[15] imem2pipe_rdata_i[15] -type PI PI
add mapped point imem2pipe_rdata_i[14] imem2pipe_rdata_i[14] -type PI PI
add mapped point imem2pipe_rdata_i[13] imem2pipe_rdata_i[13] -type PI PI
add mapped point imem2pipe_rdata_i[12] imem2pipe_rdata_i[12] -type PI PI
add mapped point imem2pipe_rdata_i[11] imem2pipe_rdata_i[11] -type PI PI
add mapped point imem2pipe_rdata_i[10] imem2pipe_rdata_i[10] -type PI PI
add mapped point imem2pipe_rdata_i[9] imem2pipe_rdata_i[9] -type PI PI
add mapped point imem2pipe_rdata_i[8] imem2pipe_rdata_i[8] -type PI PI
add mapped point imem2pipe_rdata_i[7] imem2pipe_rdata_i[7] -type PI PI
add mapped point imem2pipe_rdata_i[6] imem2pipe_rdata_i[6] -type PI PI
add mapped point imem2pipe_rdata_i[5] imem2pipe_rdata_i[5] -type PI PI
add mapped point imem2pipe_rdata_i[4] imem2pipe_rdata_i[4] -type PI PI
add mapped point imem2pipe_rdata_i[3] imem2pipe_rdata_i[3] -type PI PI
add mapped point imem2pipe_rdata_i[2] imem2pipe_rdata_i[2] -type PI PI
add mapped point imem2pipe_rdata_i[1] imem2pipe_rdata_i[1] -type PI PI
add mapped point imem2pipe_rdata_i[0] imem2pipe_rdata_i[0] -type PI PI
add mapped point imem2pipe_resp_i[1] imem2pipe_resp_i[1] -type PI PI
add mapped point imem2pipe_resp_i[0] imem2pipe_resp_i[0] -type PI PI
add mapped point dmem2pipe_req_ack_i dmem2pipe_req_ack_i -type PI PI
add mapped point dmem2pipe_rdata_i[31] dmem2pipe_rdata_i[31] -type PI PI
add mapped point dmem2pipe_rdata_i[30] dmem2pipe_rdata_i[30] -type PI PI
add mapped point dmem2pipe_rdata_i[29] dmem2pipe_rdata_i[29] -type PI PI
add mapped point dmem2pipe_rdata_i[28] dmem2pipe_rdata_i[28] -type PI PI
add mapped point dmem2pipe_rdata_i[27] dmem2pipe_rdata_i[27] -type PI PI
add mapped point dmem2pipe_rdata_i[26] dmem2pipe_rdata_i[26] -type PI PI
add mapped point dmem2pipe_rdata_i[25] dmem2pipe_rdata_i[25] -type PI PI
add mapped point dmem2pipe_rdata_i[24] dmem2pipe_rdata_i[24] -type PI PI
add mapped point dmem2pipe_rdata_i[23] dmem2pipe_rdata_i[23] -type PI PI
add mapped point dmem2pipe_rdata_i[22] dmem2pipe_rdata_i[22] -type PI PI
add mapped point dmem2pipe_rdata_i[21] dmem2pipe_rdata_i[21] -type PI PI
add mapped point dmem2pipe_rdata_i[20] dmem2pipe_rdata_i[20] -type PI PI
add mapped point dmem2pipe_rdata_i[19] dmem2pipe_rdata_i[19] -type PI PI
add mapped point dmem2pipe_rdata_i[18] dmem2pipe_rdata_i[18] -type PI PI
add mapped point dmem2pipe_rdata_i[17] dmem2pipe_rdata_i[17] -type PI PI
add mapped point dmem2pipe_rdata_i[16] dmem2pipe_rdata_i[16] -type PI PI
add mapped point dmem2pipe_rdata_i[15] dmem2pipe_rdata_i[15] -type PI PI
add mapped point dmem2pipe_rdata_i[14] dmem2pipe_rdata_i[14] -type PI PI
add mapped point dmem2pipe_rdata_i[13] dmem2pipe_rdata_i[13] -type PI PI
add mapped point dmem2pipe_rdata_i[12] dmem2pipe_rdata_i[12] -type PI PI
add mapped point dmem2pipe_rdata_i[11] dmem2pipe_rdata_i[11] -type PI PI
add mapped point dmem2pipe_rdata_i[10] dmem2pipe_rdata_i[10] -type PI PI
add mapped point dmem2pipe_rdata_i[9] dmem2pipe_rdata_i[9] -type PI PI
add mapped point dmem2pipe_rdata_i[8] dmem2pipe_rdata_i[8] -type PI PI
add mapped point dmem2pipe_rdata_i[7] dmem2pipe_rdata_i[7] -type PI PI
add mapped point dmem2pipe_rdata_i[6] dmem2pipe_rdata_i[6] -type PI PI
add mapped point dmem2pipe_rdata_i[5] dmem2pipe_rdata_i[5] -type PI PI
add mapped point dmem2pipe_rdata_i[4] dmem2pipe_rdata_i[4] -type PI PI
add mapped point dmem2pipe_rdata_i[3] dmem2pipe_rdata_i[3] -type PI PI
add mapped point dmem2pipe_rdata_i[2] dmem2pipe_rdata_i[2] -type PI PI
add mapped point dmem2pipe_rdata_i[1] dmem2pipe_rdata_i[1] -type PI PI
add mapped point dmem2pipe_rdata_i[0] dmem2pipe_rdata_i[0] -type PI PI
add mapped point dmem2pipe_resp_i[1] dmem2pipe_resp_i[1] -type PI PI
add mapped point dmem2pipe_resp_i[0] dmem2pipe_resp_i[0] -type PI PI
add mapped point soc2pipe_irq_ext_i soc2pipe_irq_ext_i -type PI PI
add mapped point soc2pipe_irq_soft_i soc2pipe_irq_soft_i -type PI PI
add mapped point soc2pipe_irq_mtimer_i soc2pipe_irq_mtimer_i -type PI PI
add mapped point soc2pipe_mtimer_val_i[63] soc2pipe_mtimer_val_i[63] -type PI PI
add mapped point soc2pipe_mtimer_val_i[62] soc2pipe_mtimer_val_i[62] -type PI PI
add mapped point soc2pipe_mtimer_val_i[61] soc2pipe_mtimer_val_i[61] -type PI PI
add mapped point soc2pipe_mtimer_val_i[60] soc2pipe_mtimer_val_i[60] -type PI PI
add mapped point soc2pipe_mtimer_val_i[59] soc2pipe_mtimer_val_i[59] -type PI PI
add mapped point soc2pipe_mtimer_val_i[58] soc2pipe_mtimer_val_i[58] -type PI PI
add mapped point soc2pipe_mtimer_val_i[57] soc2pipe_mtimer_val_i[57] -type PI PI
add mapped point soc2pipe_mtimer_val_i[56] soc2pipe_mtimer_val_i[56] -type PI PI
add mapped point soc2pipe_mtimer_val_i[55] soc2pipe_mtimer_val_i[55] -type PI PI
add mapped point soc2pipe_mtimer_val_i[54] soc2pipe_mtimer_val_i[54] -type PI PI
add mapped point soc2pipe_mtimer_val_i[53] soc2pipe_mtimer_val_i[53] -type PI PI
add mapped point soc2pipe_mtimer_val_i[52] soc2pipe_mtimer_val_i[52] -type PI PI
add mapped point soc2pipe_mtimer_val_i[51] soc2pipe_mtimer_val_i[51] -type PI PI
add mapped point soc2pipe_mtimer_val_i[50] soc2pipe_mtimer_val_i[50] -type PI PI
add mapped point soc2pipe_mtimer_val_i[49] soc2pipe_mtimer_val_i[49] -type PI PI
add mapped point soc2pipe_mtimer_val_i[48] soc2pipe_mtimer_val_i[48] -type PI PI
add mapped point soc2pipe_mtimer_val_i[47] soc2pipe_mtimer_val_i[47] -type PI PI
add mapped point soc2pipe_mtimer_val_i[46] soc2pipe_mtimer_val_i[46] -type PI PI
add mapped point soc2pipe_mtimer_val_i[45] soc2pipe_mtimer_val_i[45] -type PI PI
add mapped point soc2pipe_mtimer_val_i[44] soc2pipe_mtimer_val_i[44] -type PI PI
add mapped point soc2pipe_mtimer_val_i[43] soc2pipe_mtimer_val_i[43] -type PI PI
add mapped point soc2pipe_mtimer_val_i[42] soc2pipe_mtimer_val_i[42] -type PI PI
add mapped point soc2pipe_mtimer_val_i[41] soc2pipe_mtimer_val_i[41] -type PI PI
add mapped point soc2pipe_mtimer_val_i[40] soc2pipe_mtimer_val_i[40] -type PI PI
add mapped point soc2pipe_mtimer_val_i[39] soc2pipe_mtimer_val_i[39] -type PI PI
add mapped point soc2pipe_mtimer_val_i[38] soc2pipe_mtimer_val_i[38] -type PI PI
add mapped point soc2pipe_mtimer_val_i[37] soc2pipe_mtimer_val_i[37] -type PI PI
add mapped point soc2pipe_mtimer_val_i[36] soc2pipe_mtimer_val_i[36] -type PI PI
add mapped point soc2pipe_mtimer_val_i[35] soc2pipe_mtimer_val_i[35] -type PI PI
add mapped point soc2pipe_mtimer_val_i[34] soc2pipe_mtimer_val_i[34] -type PI PI
add mapped point soc2pipe_mtimer_val_i[33] soc2pipe_mtimer_val_i[33] -type PI PI
add mapped point soc2pipe_mtimer_val_i[32] soc2pipe_mtimer_val_i[32] -type PI PI
add mapped point soc2pipe_mtimer_val_i[31] soc2pipe_mtimer_val_i[31] -type PI PI
add mapped point soc2pipe_mtimer_val_i[30] soc2pipe_mtimer_val_i[30] -type PI PI
add mapped point soc2pipe_mtimer_val_i[29] soc2pipe_mtimer_val_i[29] -type PI PI
add mapped point soc2pipe_mtimer_val_i[28] soc2pipe_mtimer_val_i[28] -type PI PI
add mapped point soc2pipe_mtimer_val_i[27] soc2pipe_mtimer_val_i[27] -type PI PI
add mapped point soc2pipe_mtimer_val_i[26] soc2pipe_mtimer_val_i[26] -type PI PI
add mapped point soc2pipe_mtimer_val_i[25] soc2pipe_mtimer_val_i[25] -type PI PI
add mapped point soc2pipe_mtimer_val_i[24] soc2pipe_mtimer_val_i[24] -type PI PI
add mapped point soc2pipe_mtimer_val_i[23] soc2pipe_mtimer_val_i[23] -type PI PI
add mapped point soc2pipe_mtimer_val_i[22] soc2pipe_mtimer_val_i[22] -type PI PI
add mapped point soc2pipe_mtimer_val_i[21] soc2pipe_mtimer_val_i[21] -type PI PI
add mapped point soc2pipe_mtimer_val_i[20] soc2pipe_mtimer_val_i[20] -type PI PI
add mapped point soc2pipe_mtimer_val_i[19] soc2pipe_mtimer_val_i[19] -type PI PI
add mapped point soc2pipe_mtimer_val_i[18] soc2pipe_mtimer_val_i[18] -type PI PI
add mapped point soc2pipe_mtimer_val_i[17] soc2pipe_mtimer_val_i[17] -type PI PI
add mapped point soc2pipe_mtimer_val_i[16] soc2pipe_mtimer_val_i[16] -type PI PI
add mapped point soc2pipe_mtimer_val_i[15] soc2pipe_mtimer_val_i[15] -type PI PI
add mapped point soc2pipe_mtimer_val_i[14] soc2pipe_mtimer_val_i[14] -type PI PI
add mapped point soc2pipe_mtimer_val_i[13] soc2pipe_mtimer_val_i[13] -type PI PI
add mapped point soc2pipe_mtimer_val_i[12] soc2pipe_mtimer_val_i[12] -type PI PI
add mapped point soc2pipe_mtimer_val_i[11] soc2pipe_mtimer_val_i[11] -type PI PI
add mapped point soc2pipe_mtimer_val_i[10] soc2pipe_mtimer_val_i[10] -type PI PI
add mapped point soc2pipe_mtimer_val_i[9] soc2pipe_mtimer_val_i[9] -type PI PI
add mapped point soc2pipe_mtimer_val_i[8] soc2pipe_mtimer_val_i[8] -type PI PI
add mapped point soc2pipe_mtimer_val_i[7] soc2pipe_mtimer_val_i[7] -type PI PI
add mapped point soc2pipe_mtimer_val_i[6] soc2pipe_mtimer_val_i[6] -type PI PI
add mapped point soc2pipe_mtimer_val_i[5] soc2pipe_mtimer_val_i[5] -type PI PI
add mapped point soc2pipe_mtimer_val_i[4] soc2pipe_mtimer_val_i[4] -type PI PI
add mapped point soc2pipe_mtimer_val_i[3] soc2pipe_mtimer_val_i[3] -type PI PI
add mapped point soc2pipe_mtimer_val_i[2] soc2pipe_mtimer_val_i[2] -type PI PI
add mapped point soc2pipe_mtimer_val_i[1] soc2pipe_mtimer_val_i[1] -type PI PI
add mapped point soc2pipe_mtimer_val_i[0] soc2pipe_mtimer_val_i[0] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[31] soc2pipe_fuse_mhartid_i[31] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[30] soc2pipe_fuse_mhartid_i[30] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[29] soc2pipe_fuse_mhartid_i[29] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[28] soc2pipe_fuse_mhartid_i[28] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[27] soc2pipe_fuse_mhartid_i[27] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[26] soc2pipe_fuse_mhartid_i[26] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[25] soc2pipe_fuse_mhartid_i[25] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[24] soc2pipe_fuse_mhartid_i[24] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[23] soc2pipe_fuse_mhartid_i[23] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[22] soc2pipe_fuse_mhartid_i[22] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[21] soc2pipe_fuse_mhartid_i[21] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[20] soc2pipe_fuse_mhartid_i[20] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[19] soc2pipe_fuse_mhartid_i[19] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[18] soc2pipe_fuse_mhartid_i[18] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[17] soc2pipe_fuse_mhartid_i[17] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[16] soc2pipe_fuse_mhartid_i[16] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[15] soc2pipe_fuse_mhartid_i[15] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[14] soc2pipe_fuse_mhartid_i[14] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[13] soc2pipe_fuse_mhartid_i[13] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[12] soc2pipe_fuse_mhartid_i[12] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[11] soc2pipe_fuse_mhartid_i[11] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[10] soc2pipe_fuse_mhartid_i[10] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[9] soc2pipe_fuse_mhartid_i[9] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[8] soc2pipe_fuse_mhartid_i[8] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[7] soc2pipe_fuse_mhartid_i[7] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[6] soc2pipe_fuse_mhartid_i[6] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[5] soc2pipe_fuse_mhartid_i[5] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[4] soc2pipe_fuse_mhartid_i[4] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[3] soc2pipe_fuse_mhartid_i[3] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[2] soc2pipe_fuse_mhartid_i[2] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[1] soc2pipe_fuse_mhartid_i[1] -type PI PI
add mapped point soc2pipe_fuse_mhartid_i[0] soc2pipe_fuse_mhartid_i[0] -type PI PI

//output ports
add mapped point pipe2imem_req_o pipe2imem_req_o -type PO PO
add mapped point pipe2imem_cmd_o pipe2imem_cmd_o -type PO PO
add mapped point pipe2imem_addr_o[31] pipe2imem_addr_o[31] -type PO PO
add mapped point pipe2imem_addr_o[30] pipe2imem_addr_o[30] -type PO PO
add mapped point pipe2imem_addr_o[29] pipe2imem_addr_o[29] -type PO PO
add mapped point pipe2imem_addr_o[28] pipe2imem_addr_o[28] -type PO PO
add mapped point pipe2imem_addr_o[27] pipe2imem_addr_o[27] -type PO PO
add mapped point pipe2imem_addr_o[26] pipe2imem_addr_o[26] -type PO PO
add mapped point pipe2imem_addr_o[25] pipe2imem_addr_o[25] -type PO PO
add mapped point pipe2imem_addr_o[24] pipe2imem_addr_o[24] -type PO PO
add mapped point pipe2imem_addr_o[23] pipe2imem_addr_o[23] -type PO PO
add mapped point pipe2imem_addr_o[22] pipe2imem_addr_o[22] -type PO PO
add mapped point pipe2imem_addr_o[21] pipe2imem_addr_o[21] -type PO PO
add mapped point pipe2imem_addr_o[20] pipe2imem_addr_o[20] -type PO PO
add mapped point pipe2imem_addr_o[19] pipe2imem_addr_o[19] -type PO PO
add mapped point pipe2imem_addr_o[18] pipe2imem_addr_o[18] -type PO PO
add mapped point pipe2imem_addr_o[17] pipe2imem_addr_o[17] -type PO PO
add mapped point pipe2imem_addr_o[16] pipe2imem_addr_o[16] -type PO PO
add mapped point pipe2imem_addr_o[15] pipe2imem_addr_o[15] -type PO PO
add mapped point pipe2imem_addr_o[14] pipe2imem_addr_o[14] -type PO PO
add mapped point pipe2imem_addr_o[13] pipe2imem_addr_o[13] -type PO PO
add mapped point pipe2imem_addr_o[12] pipe2imem_addr_o[12] -type PO PO
add mapped point pipe2imem_addr_o[11] pipe2imem_addr_o[11] -type PO PO
add mapped point pipe2imem_addr_o[10] pipe2imem_addr_o[10] -type PO PO
add mapped point pipe2imem_addr_o[9] pipe2imem_addr_o[9] -type PO PO
add mapped point pipe2imem_addr_o[8] pipe2imem_addr_o[8] -type PO PO
add mapped point pipe2imem_addr_o[7] pipe2imem_addr_o[7] -type PO PO
add mapped point pipe2imem_addr_o[6] pipe2imem_addr_o[6] -type PO PO
add mapped point pipe2imem_addr_o[5] pipe2imem_addr_o[5] -type PO PO
add mapped point pipe2imem_addr_o[4] pipe2imem_addr_o[4] -type PO PO
add mapped point pipe2imem_addr_o[3] pipe2imem_addr_o[3] -type PO PO
add mapped point pipe2imem_addr_o[2] pipe2imem_addr_o[2] -type PO PO
add mapped point pipe2imem_addr_o[1] pipe2imem_addr_o[1] -type PO PO
add mapped point pipe2imem_addr_o[0] pipe2imem_addr_o[0] -type PO PO
add mapped point pipe2dmem_req_o pipe2dmem_req_o -type PO PO
add mapped point pipe2dmem_cmd_o pipe2dmem_cmd_o -type PO PO
add mapped point pipe2dmem_width_o[1] pipe2dmem_width_o[1] -type PO PO
add mapped point pipe2dmem_width_o[0] pipe2dmem_width_o[0] -type PO PO
add mapped point pipe2dmem_addr_o[31] pipe2dmem_addr_o[31] -type PO PO
add mapped point pipe2dmem_addr_o[30] pipe2dmem_addr_o[30] -type PO PO
add mapped point pipe2dmem_addr_o[29] pipe2dmem_addr_o[29] -type PO PO
add mapped point pipe2dmem_addr_o[28] pipe2dmem_addr_o[28] -type PO PO
add mapped point pipe2dmem_addr_o[27] pipe2dmem_addr_o[27] -type PO PO
add mapped point pipe2dmem_addr_o[26] pipe2dmem_addr_o[26] -type PO PO
add mapped point pipe2dmem_addr_o[25] pipe2dmem_addr_o[25] -type PO PO
add mapped point pipe2dmem_addr_o[24] pipe2dmem_addr_o[24] -type PO PO
add mapped point pipe2dmem_addr_o[23] pipe2dmem_addr_o[23] -type PO PO
add mapped point pipe2dmem_addr_o[22] pipe2dmem_addr_o[22] -type PO PO
add mapped point pipe2dmem_addr_o[21] pipe2dmem_addr_o[21] -type PO PO
add mapped point pipe2dmem_addr_o[20] pipe2dmem_addr_o[20] -type PO PO
add mapped point pipe2dmem_addr_o[19] pipe2dmem_addr_o[19] -type PO PO
add mapped point pipe2dmem_addr_o[18] pipe2dmem_addr_o[18] -type PO PO
add mapped point pipe2dmem_addr_o[17] pipe2dmem_addr_o[17] -type PO PO
add mapped point pipe2dmem_addr_o[16] pipe2dmem_addr_o[16] -type PO PO
add mapped point pipe2dmem_addr_o[15] pipe2dmem_addr_o[15] -type PO PO
add mapped point pipe2dmem_addr_o[14] pipe2dmem_addr_o[14] -type PO PO
add mapped point pipe2dmem_addr_o[13] pipe2dmem_addr_o[13] -type PO PO
add mapped point pipe2dmem_addr_o[12] pipe2dmem_addr_o[12] -type PO PO
add mapped point pipe2dmem_addr_o[11] pipe2dmem_addr_o[11] -type PO PO
add mapped point pipe2dmem_addr_o[10] pipe2dmem_addr_o[10] -type PO PO
add mapped point pipe2dmem_addr_o[9] pipe2dmem_addr_o[9] -type PO PO
add mapped point pipe2dmem_addr_o[8] pipe2dmem_addr_o[8] -type PO PO
add mapped point pipe2dmem_addr_o[7] pipe2dmem_addr_o[7] -type PO PO
add mapped point pipe2dmem_addr_o[6] pipe2dmem_addr_o[6] -type PO PO
add mapped point pipe2dmem_addr_o[5] pipe2dmem_addr_o[5] -type PO PO
add mapped point pipe2dmem_addr_o[4] pipe2dmem_addr_o[4] -type PO PO
add mapped point pipe2dmem_addr_o[3] pipe2dmem_addr_o[3] -type PO PO
add mapped point pipe2dmem_addr_o[2] pipe2dmem_addr_o[2] -type PO PO
add mapped point pipe2dmem_addr_o[1] pipe2dmem_addr_o[1] -type PO PO
add mapped point pipe2dmem_addr_o[0] pipe2dmem_addr_o[0] -type PO PO
add mapped point pipe2dmem_wdata_o[31] pipe2dmem_wdata_o[31] -type PO PO
add mapped point pipe2dmem_wdata_o[30] pipe2dmem_wdata_o[30] -type PO PO
add mapped point pipe2dmem_wdata_o[29] pipe2dmem_wdata_o[29] -type PO PO
add mapped point pipe2dmem_wdata_o[28] pipe2dmem_wdata_o[28] -type PO PO
add mapped point pipe2dmem_wdata_o[27] pipe2dmem_wdata_o[27] -type PO PO
add mapped point pipe2dmem_wdata_o[26] pipe2dmem_wdata_o[26] -type PO PO
add mapped point pipe2dmem_wdata_o[25] pipe2dmem_wdata_o[25] -type PO PO
add mapped point pipe2dmem_wdata_o[24] pipe2dmem_wdata_o[24] -type PO PO
add mapped point pipe2dmem_wdata_o[23] pipe2dmem_wdata_o[23] -type PO PO
add mapped point pipe2dmem_wdata_o[22] pipe2dmem_wdata_o[22] -type PO PO
add mapped point pipe2dmem_wdata_o[21] pipe2dmem_wdata_o[21] -type PO PO
add mapped point pipe2dmem_wdata_o[20] pipe2dmem_wdata_o[20] -type PO PO
add mapped point pipe2dmem_wdata_o[19] pipe2dmem_wdata_o[19] -type PO PO
add mapped point pipe2dmem_wdata_o[18] pipe2dmem_wdata_o[18] -type PO PO
add mapped point pipe2dmem_wdata_o[17] pipe2dmem_wdata_o[17] -type PO PO
add mapped point pipe2dmem_wdata_o[16] pipe2dmem_wdata_o[16] -type PO PO
add mapped point pipe2dmem_wdata_o[15] pipe2dmem_wdata_o[15] -type PO PO
add mapped point pipe2dmem_wdata_o[14] pipe2dmem_wdata_o[14] -type PO PO
add mapped point pipe2dmem_wdata_o[13] pipe2dmem_wdata_o[13] -type PO PO
add mapped point pipe2dmem_wdata_o[12] pipe2dmem_wdata_o[12] -type PO PO
add mapped point pipe2dmem_wdata_o[11] pipe2dmem_wdata_o[11] -type PO PO
add mapped point pipe2dmem_wdata_o[10] pipe2dmem_wdata_o[10] -type PO PO
add mapped point pipe2dmem_wdata_o[9] pipe2dmem_wdata_o[9] -type PO PO
add mapped point pipe2dmem_wdata_o[8] pipe2dmem_wdata_o[8] -type PO PO
add mapped point pipe2dmem_wdata_o[7] pipe2dmem_wdata_o[7] -type PO PO
add mapped point pipe2dmem_wdata_o[6] pipe2dmem_wdata_o[6] -type PO PO
add mapped point pipe2dmem_wdata_o[5] pipe2dmem_wdata_o[5] -type PO PO
add mapped point pipe2dmem_wdata_o[4] pipe2dmem_wdata_o[4] -type PO PO
add mapped point pipe2dmem_wdata_o[3] pipe2dmem_wdata_o[3] -type PO PO
add mapped point pipe2dmem_wdata_o[2] pipe2dmem_wdata_o[2] -type PO PO
add mapped point pipe2dmem_wdata_o[1] pipe2dmem_wdata_o[1] -type PO PO
add mapped point pipe2dmem_wdata_o[0] pipe2dmem_wdata_o[0] -type PO PO
add mapped point clkout clkout -type PO PO

//inout ports




//Sequential Pins
add mapped point i_pipe_exu/exu_queue.exc_req/q i_pipe_exu_exu_queue_reg[exc_req]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.jump_req/q i_pipe_exu_exu_queue_reg[jump_req]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.mret_req/q i_pipe_exu_exu_queue_reg[mret_req]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.rd_wb_sel[0]/q i_pipe_exu_exu_queue_reg[rd_wb_sel][0]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.rd_wb_sel[1]/q i_pipe_exu_exu_queue_reg[rd_wb_sel][1]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.rd_wb_sel[2]/q i_pipe_exu_exu_queue_reg[rd_wb_sel][2]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.rs2_addr[0]/q i_pipe_exu_exu_queue_reg[rs2_addr][0]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.rs2_addr[1]/q i_pipe_exu_exu_queue_reg[rs2_addr][1]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.rs2_addr[2]/q i_pipe_exu_exu_queue_reg[rs2_addr][2]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.rs2_addr[3]/q i_pipe_exu_exu_queue_reg[rs2_addr][3]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.rs2_addr[4]/q i_pipe_exu_exu_queue_reg[rs2_addr][4]/Q  -type DFF DFF
add mapped point i_pipe_exu/i_lsu/lsu_cmd_ff[0]/q i_pipe_exu_i_lsu_lsu_cmd_ff_reg[0]/Q  -type DFF DFF
add mapped point i_pipe_exu/idu2exu_use_rs2_ff/q i_pipe_exu_idu2exu_use_rs2_ff_reg/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_err[0]/q i_pipe_ifu_q_err_reg[0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_err[2]/q i_pipe_ifu_q_err_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_exu/i_lsu/lsu_cmd_ff[1]/q i_pipe_exu_i_lsu_lsu_cmd_ff_reg[1]/Q  -type DFF DFF
add mapped point i_pipe_exu/i_lsu/lsu_cmd_ff[2]/q i_pipe_exu_i_lsu_lsu_cmd_ff_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_exu/i_lsu/lsu_cmd_ff[3]/q i_pipe_exu_i_lsu_lsu_cmd_ff_reg[3]/Q  -type DFF DFF
add mapped point i_pipe_exu/init_pc_v[0]/q i_pipe_exu_init_pc_v_reg[0]/Q  -type DFF DFF
add mapped point i_pipe_exu/init_pc_v[1]/q i_pipe_exu_init_pc_v_reg[1]/Q  -type DFF DFF
add mapped point i_pipe_exu/init_pc_v[2]/q i_pipe_exu_init_pc_v_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_exu/init_pc_v[3]/q i_pipe_exu_init_pc_v_reg[3]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][2]/q i_pipe_ifu_q_data_reg[0][2]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][3]/q i_pipe_ifu_q_data_reg[0][3]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][4]/q i_pipe_ifu_q_data_reg[0][4]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][6]/q i_pipe_ifu_q_data_reg[0][6]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][7]/q i_pipe_ifu_q_data_reg[0][7]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][8]/q i_pipe_ifu_q_data_reg[0][8]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][9]/q i_pipe_ifu_q_data_reg[0][9]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][10]/q i_pipe_ifu_q_data_reg[0][10]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][11]/q i_pipe_ifu_q_data_reg[0][11]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][12]/q i_pipe_ifu_q_data_reg[0][12]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][14]/q i_pipe_ifu_q_data_reg[0][14]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][15]/q i_pipe_ifu_q_data_reg[0][15]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][4]/q i_pipe_ifu_q_data_reg[1][4]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][6]/q i_pipe_ifu_q_data_reg[1][6]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][7]/q i_pipe_ifu_q_data_reg[1][7]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][8]/q i_pipe_ifu_q_data_reg[1][8]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][9]/q i_pipe_ifu_q_data_reg[1][9]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][10]/q i_pipe_ifu_q_data_reg[1][10]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][11]/q i_pipe_ifu_q_data_reg[1][11]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][12]/q i_pipe_ifu_q_data_reg[1][12]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][14]/q i_pipe_ifu_q_data_reg[1][14]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][15]/q i_pipe_ifu_q_data_reg[1][15]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][2]/q i_pipe_ifu_q_data_reg[2][2]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][4]/q i_pipe_ifu_q_data_reg[2][4]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][6]/q i_pipe_ifu_q_data_reg[2][6]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][7]/q i_pipe_ifu_q_data_reg[2][7]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][8]/q i_pipe_ifu_q_data_reg[2][8]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][9]/q i_pipe_ifu_q_data_reg[2][9]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][10]/q i_pipe_ifu_q_data_reg[2][10]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][11]/q i_pipe_ifu_q_data_reg[2][11]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][12]/q i_pipe_ifu_q_data_reg[2][12]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][14]/q i_pipe_ifu_q_data_reg[2][14]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][15]/q i_pipe_ifu_q_data_reg[2][15]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][2]/q i_pipe_ifu_q_data_reg[3][2]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][3]/q i_pipe_ifu_q_data_reg[3][3]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][4]/q i_pipe_ifu_q_data_reg[3][4]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][5]/q i_pipe_ifu_q_data_reg[3][5]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][6]/q i_pipe_ifu_q_data_reg[3][6]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][7]/q i_pipe_ifu_q_data_reg[3][7]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][8]/q i_pipe_ifu_q_data_reg[3][8]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][9]/q i_pipe_ifu_q_data_reg[3][9]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][10]/q i_pipe_ifu_q_data_reg[3][10]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][11]/q i_pipe_ifu_q_data_reg[3][11]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][12]/q i_pipe_ifu_q_data_reg[3][12]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][13]/q i_pipe_ifu_q_data_reg[3][13]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][14]/q i_pipe_ifu_q_data_reg[3][14]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][15]/q i_pipe_ifu_q_data_reg[3][15]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_err[1]/q i_pipe_ifu_q_err_reg[1]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_err[3]/q i_pipe_ifu_q_err_reg[3]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.branch_req/q i_pipe_exu_exu_queue_reg[branch_req]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.ialu_cmd[0]/q i_pipe_exu_exu_queue_reg[ialu_cmd][0]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.ialu_cmd[1]/q i_pipe_exu_exu_queue_reg[ialu_cmd][1]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.ialu_cmd[2]/q i_pipe_exu_exu_queue_reg[ialu_cmd][2]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.ialu_cmd[3]/q i_pipe_exu_exu_queue_reg[ialu_cmd][3]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.ialu_op[0]/q i_pipe_exu_exu_queue_reg[ialu_op][0]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[0]/q i_pipe_exu_exu_queue_reg[imm][0]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[1]/q i_pipe_exu_exu_queue_reg[imm][1]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[12]/q i_pipe_exu_exu_queue_reg[imm][12]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[13]/q i_pipe_exu_exu_queue_reg[imm][13]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[14]/q i_pipe_exu_exu_queue_reg[imm][14]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.lsu_cmd[0]/q i_pipe_exu_exu_queue_reg[lsu_cmd][0]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.lsu_cmd[1]/q i_pipe_exu_exu_queue_reg[lsu_cmd][1]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.lsu_cmd[2]/q i_pipe_exu_exu_queue_reg[lsu_cmd][2]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.lsu_cmd[3]/q i_pipe_exu_exu_queue_reg[lsu_cmd][3]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.sum2_op[0]/q i_pipe_exu_exu_queue_reg[sum2_op][0]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.wfi_req/q i_pipe_exu_exu_queue_reg[wfi_req]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[9]/q i_pipe_exu_pc_curr_ff_reg[9]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[2]/q i_pipe_ifu_imem_addr_ff_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[3]/q i_pipe_ifu_imem_addr_ff_reg[3]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[4]/q i_pipe_ifu_imem_addr_ff_reg[4]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[5]/q i_pipe_ifu_imem_addr_ff_reg[5]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[6]/q i_pipe_ifu_imem_addr_ff_reg[6]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[7]/q i_pipe_ifu_imem_addr_ff_reg[7]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[8]/q i_pipe_ifu_imem_addr_ff_reg[8]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[9]/q i_pipe_ifu_imem_addr_ff_reg[9]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[11]/q i_pipe_ifu_imem_addr_ff_reg[11]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[12]/q i_pipe_ifu_imem_addr_ff_reg[12]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[13]/q i_pipe_ifu_imem_addr_ff_reg[13]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[14]/q i_pipe_ifu_imem_addr_ff_reg[14]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[17]/q i_pipe_ifu_imem_addr_ff_reg[17]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[20]/q i_pipe_ifu_imem_addr_ff_reg[20]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[21]/q i_pipe_ifu_imem_addr_ff_reg[21]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[22]/q i_pipe_ifu_imem_addr_ff_reg[22]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[23]/q i_pipe_ifu_imem_addr_ff_reg[23]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[24]/q i_pipe_ifu_imem_addr_ff_reg[24]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[25]/q i_pipe_ifu_imem_addr_ff_reg[25]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[26]/q i_pipe_ifu_imem_addr_ff_reg[26]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[27]/q i_pipe_ifu_imem_addr_ff_reg[27]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[28]/q i_pipe_ifu_imem_addr_ff_reg[28]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[31]/q i_pipe_ifu_imem_addr_ff_reg[31]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_pnd_txns_cnt[1]/q i_pipe_ifu_imem_pnd_txns_cnt_reg[1]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_resp_discard_cnt[0]/q i_pipe_ifu_imem_resp_discard_cnt_reg[0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_resp_discard_cnt[1]/q i_pipe_ifu_imem_resp_discard_cnt_reg[1]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue_vd_ff/q i_pipe_exu_exu_queue_vd_ff_reg/Q  -type DFF DFF
add mapped point i_pipe_exu/i_lsu/lsu_fsm_curr/q i_pipe_exu_i_lsu_lsu_fsm_curr_reg/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[2]/q i_pipe_exu_pc_curr_ff_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[3]/q i_pipe_exu_pc_curr_ff_reg[3]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[4]/q i_pipe_exu_pc_curr_ff_reg[4]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[5]/q i_pipe_exu_pc_curr_ff_reg[5]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[6]/q i_pipe_exu_pc_curr_ff_reg[6]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[7]/q i_pipe_exu_pc_curr_ff_reg[7]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[8]/q i_pipe_exu_pc_curr_ff_reg[8]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[10]/q i_pipe_exu_pc_curr_ff_reg[10]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[11]/q i_pipe_exu_pc_curr_ff_reg[11]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[12]/q i_pipe_exu_pc_curr_ff_reg[12]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[13]/q i_pipe_exu_pc_curr_ff_reg[13]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[14]/q i_pipe_exu_pc_curr_ff_reg[14]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[15]/q i_pipe_exu_pc_curr_ff_reg[15]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[16]/q i_pipe_exu_pc_curr_ff_reg[16]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[17]/q i_pipe_exu_pc_curr_ff_reg[17]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[18]/q i_pipe_exu_pc_curr_ff_reg[18]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[19]/q i_pipe_exu_pc_curr_ff_reg[19]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[20]/q i_pipe_exu_pc_curr_ff_reg[20]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[21]/q i_pipe_exu_pc_curr_ff_reg[21]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[22]/q i_pipe_exu_pc_curr_ff_reg[22]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[23]/q i_pipe_exu_pc_curr_ff_reg[23]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[24]/q i_pipe_exu_pc_curr_ff_reg[24]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[25]/q i_pipe_exu_pc_curr_ff_reg[25]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[26]/q i_pipe_exu_pc_curr_ff_reg[26]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[27]/q i_pipe_exu_pc_curr_ff_reg[27]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[28]/q i_pipe_exu_pc_curr_ff_reg[28]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[29]/q i_pipe_exu_pc_curr_ff_reg[29]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[30]/q i_pipe_exu_pc_curr_ff_reg[30]/Q  -type DFF DFF
add mapped point i_pipe_exu/pc_curr_ff[31]/q i_pipe_exu_pc_curr_ff_reg[31]/Q  -type DFF DFF
add mapped point i_pipe_exu/wfi_halted_ff/q i_pipe_exu_wfi_halted_ff_reg/Q  -type DFF DFF
add mapped point i_pipe_ifu/ifu_fsm_curr/q i_pipe_ifu_ifu_fsm_curr_reg/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[10]/q i_pipe_ifu_imem_addr_ff_reg[10]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[15]/q i_pipe_ifu_imem_addr_ff_reg[15]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[16]/q i_pipe_ifu_imem_addr_ff_reg[16]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[18]/q i_pipe_ifu_imem_addr_ff_reg[18]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[19]/q i_pipe_ifu_imem_addr_ff_reg[19]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[29]/q i_pipe_ifu_imem_addr_ff_reg[29]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_addr_ff[30]/q i_pipe_ifu_imem_addr_ff_reg[30]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_pnd_txns_cnt[0]/q i_pipe_ifu_imem_pnd_txns_cnt_reg[0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_pnd_txns_cnt[2]/q i_pipe_ifu_imem_pnd_txns_cnt_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_ifu/imem_resp_discard_cnt[2]/q i_pipe_ifu_imem_resp_discard_cnt_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_ifu/instr_hi_rvi_lo_ff/q i_pipe_ifu_instr_hi_rvi_lo_ff_reg/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][0]/q i_pipe_ifu_q_data_reg[0][0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][1]/q i_pipe_ifu_q_data_reg[0][1]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][5]/q i_pipe_ifu_q_data_reg[0][5]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[0][13]/q i_pipe_ifu_q_data_reg[0][13]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][0]/q i_pipe_ifu_q_data_reg[1][0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][1]/q i_pipe_ifu_q_data_reg[1][1]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][2]/q i_pipe_ifu_q_data_reg[1][2]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][3]/q i_pipe_ifu_q_data_reg[1][3]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][5]/q i_pipe_ifu_q_data_reg[1][5]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[1][13]/q i_pipe_ifu_q_data_reg[1][13]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][0]/q i_pipe_ifu_q_data_reg[2][0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][1]/q i_pipe_ifu_q_data_reg[2][1]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][3]/q i_pipe_ifu_q_data_reg[2][3]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][5]/q i_pipe_ifu_q_data_reg[2][5]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[2][13]/q i_pipe_ifu_q_data_reg[2][13]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][0]/q i_pipe_ifu_q_data_reg[3][0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_data[3][1]/q i_pipe_ifu_q_data_reg[3][1]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_rptr[0]/q i_pipe_ifu_q_rptr_reg[0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_rptr[1]/q i_pipe_ifu_q_rptr_reg[1]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_rptr[2]/q i_pipe_ifu_q_rptr_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_wptr[0]/q i_pipe_ifu_q_wptr_reg[0]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_wptr[1]/q i_pipe_ifu_q_wptr_reg[1]/Q  -type DFF DFF
add mapped point i_pipe_ifu/q_wptr[2]/q i_pipe_ifu_q_wptr_reg[2]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.fencei_req/q i_pipe_exu_exu_queue_reg[fencei_req]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[2]/q i_pipe_exu_exu_queue_reg[imm][2]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[3]/q i_pipe_exu_exu_queue_reg[imm][3]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[4]/q i_pipe_exu_exu_queue_reg[imm][4]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[5]/q i_pipe_exu_exu_queue_reg[imm][5]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[6]/q i_pipe_exu_exu_queue_reg[imm][6]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[7]/q i_pipe_exu_exu_queue_reg[imm][7]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[8]/q i_pipe_exu_exu_queue_reg[imm][8]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[9]/q i_pipe_exu_exu_queue_reg[imm][9]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[10]/q i_pipe_exu_exu_queue_reg[imm][10]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[11]/q i_pipe_exu_exu_queue_reg[imm][11]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[15]/q i_pipe_exu_exu_queue_reg[imm][15]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[16]/q i_pipe_exu_exu_queue_reg[imm][16]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[17]/q i_pipe_exu_exu_queue_reg[imm][17]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[18]/q i_pipe_exu_exu_queue_reg[imm][18]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[19]/q i_pipe_exu_exu_queue_reg[imm][19]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[20]/q i_pipe_exu_exu_queue_reg[imm][20]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[21]/q i_pipe_exu_exu_queue_reg[imm][21]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[22]/q i_pipe_exu_exu_queue_reg[imm][22]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[23]/q i_pipe_exu_exu_queue_reg[imm][23]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[24]/q i_pipe_exu_exu_queue_reg[imm][24]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[25]/q i_pipe_exu_exu_queue_reg[imm][25]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[26]/q i_pipe_exu_exu_queue_reg[imm][26]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[27]/q i_pipe_exu_exu_queue_reg[imm][27]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[28]/q i_pipe_exu_exu_queue_reg[imm][28]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[29]/q i_pipe_exu_exu_queue_reg[imm][29]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[30]/q i_pipe_exu_exu_queue_reg[imm][30]/Q  -type DFF DFF
add mapped point i_pipe_exu/exu_queue.imm[31]/q i_pipe_exu_exu_queue_reg[imm][31]/Q  -type DFF DFF



//Black Boxes
add mapped point i2c_master_top_inst1 i2c_master_top_inst1 -type BBOX BBOX
add mapped point sram_32_1024_scl180_ram1 sram_32_1024_scl180_ram1 -type BBOX BBOX
add mapped point sram_32_1024_scl180_ram2 sram_32_1024_scl180_ram2 -type BBOX BBOX
add mapped point sram_32_1024_scl180_ram3 sram_32_1024_scl180_ram3 -type BBOX BBOX
add mapped point sram_32_1024_scl180_ram4 sram_32_1024_scl180_ram4 -type BBOX BBOX
add mapped point sram_32_1024_scl180_ram5 sram_32_1024_scl180_ram5 -type BBOX BBOX
add mapped point sram_32_1024_scl180_ram6 sram_32_1024_scl180_ram6 -type BBOX BBOX
add mapped point sram_32_1024_scl180_ram7 sram_32_1024_scl180_ram7 -type BBOX BBOX
add mapped point sram_32_1024_scl180_ram8 sram_32_1024_scl180_ram8 -type BBOX BBOX
add mapped point uart_inst1 uart_inst1 -type BBOX BBOX



//Empty Modules as Blackboxes
